kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-nginx2
spec:
  podSelector:
    matchLabels:
      app: nginx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx2
    ports:
      - port: 80
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-nginx-return
spec:
  podSelector:
    matchLabels:
      app: nginx
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: nginx2
    ports:
    - port: 80